#!/usr/bin/env python
import argparse
import os
import sys
import re
import logging
from schedules_tools import discovery, converter

logger = logging.getLogger(__name__)
handler_class_template = re.compile('^ScheduleHandler_(\S+)$')
VALID_MODULE_NAME = re.compile(r'^(\w+)\.py$', re.IGNORECASE)
BASE_DIR = os.path.dirname(os.path.realpath(
    os.path.join(__file__, os.pardir)))
PARENT_DIRNAME = os.path.basename(os.path.dirname(os.path.realpath(__file__)))

# FIXME(mpavlase): Figure out nicer way to deal with paths
sys.path.append(BASE_DIR)


def setup_logging(level):
    log_format = '%(name)-10s %(levelname)7s: %(message)s'
    sh = logging.StreamHandler(sys.stdout)
    sh.setLevel(level)

    formatter = logging.Formatter(log_format)
    sh.setFormatter(formatter)

    # setup root logger
    inst = logging.getLogger('')
    inst.setLevel(level)
    inst.addHandler(sh)


def main(args):
    handlers_args_def = '--handlers-path',
    handlers_kwargs_def = {
        'help': 'Add python-dot-notation path to discover handlers (needs to '
                'be python module), can be called several times '
                '(conflicting names will be overriden - the last '
                'implementation will be used)',
        'action': 'append',
        'default': []
    }
    setup_logging(logging.DEBUG)

    add_handler_parser = argparse.ArgumentParser(add_help=False)
    add_handler_parser.add_argument(*handlers_args_def, **handlers_kwargs_def)
    known_args = add_handler_parser.parse_known_args(args)

    opt_args = vars(known_args[0])  # 0. index contains successfully parsed args
    for path in opt_args.pop('handlers_path'):
        discovery.storage_handlers.add_discover_path(path)

    parser = argparse.ArgumentParser(
        description=('Entry point of automated building changed schedules. '
                     'Input provides up-to-date source (directory) and list of '
                     'changed files for further processing.'))

    parser.add_argument(*handlers_args_def, **handlers_kwargs_def)

    parser.add_argument('--source-storage-format',
                        choices=discovery.storage_handlers.keys(),
                        metavar='SRC_STORAGE_FORMAT',
                        help='Source storage format to use')
    parser.add_argument('--cvs-checkout-path',
                        help='Path to shared working copy of CVS repository')
    parser.add_argument('--cvs-repo-name',
                        help='Name of CVS repository to checkout')
    parser.add_argument('--cvs-root',
                        help='Root of CVS repository')
    parser.add_argument('source',
                        help='Source schedule handle (file/URL/...)',
                        type=str,
                        metavar='SRC')

    arguments = parser.parse_args(args)
    opt_args = vars(arguments)

    # --handlers-path argument is already processed, it shouldn't be passed
    # as opt_args into handlers
    opt_args.pop('handlers_path')

    conv = converter.ScheduleConverter()
    sch = conv.import_schedule(arguments.source, handler_opt_args=opt_args)

    print sch.name
    print sch.project_name


if __name__ == '__main__':
    main(sys.argv[1:])
