#!/usr/bin/env python
import argparse
import os
import sys
import re
import logging
from schedules_tools import discovery, converter

logger = logging.getLogger(__name__)
handler_class_template = re.compile('^ScheduleHandler_(\S+)$')
VALID_MODULE_NAME = re.compile(r'^(\w+)\.py$', re.IGNORECASE)
BASE_DIR = os.path.dirname(os.path.realpath(
    os.path.join(__file__, os.pardir)))
PARENT_DIRNAME = os.path.basename(os.path.dirname(os.path.realpath(__file__)))

# TODO: Rename script to get_local_handle

# FIXME(mpavlase): Figure out nicer way to deal with paths
sys.path.append(BASE_DIR)


def setup_logging(level):
    log_format = '%(name)-10s %(levelname)7s: %(message)s'
    sh = logging.StreamHandler(sys.stdout)
    sh.setLevel(level)

    formatter = logging.Formatter(log_format)
    sh.setFormatter(formatter)

    # setup root logger
    inst = logging.getLogger('')
    inst.setLevel(level)
    inst.addHandler(sh)


class StorageUpdate(object):
    storage_handler = None
    handle = None

    def __init__(self, handle, source_storage_format, handler_opt_args):
        self.handle = handle
        conv = converter.ScheduleConverter()
        storage_handler_cls = conv.get_storage_handler_cls(source_storage_format)
        self.storage_handler = storage_handler_cls(opt_args=handler_opt_args)
        self.storage_handler.clone()
        self.update()

    def update(self):
        changed_paths = self.storage_handler.update(self.handle)
        logger.debug('changed paths: {}'.format(changed_paths))


def main(args):
    handlers_args_def = '--handlers-path',
    handlers_kwargs_def = {
        'help': 'Add path to discover handlers (needs to be python'
                ' module), can be called several times '
                '(conflicting names will be overriden - the last '
                'implementation will be used)',
        'action': 'append',
        'default': []
    }
    setup_logging(logging.DEBUG)

    add_handler_parser = argparse.ArgumentParser(add_help=False)
    add_handler_parser.add_argument(*handlers_args_def, **handlers_kwargs_def)
    known_args = add_handler_parser.parse_known_args(args)

    opt_args = vars(known_args[0])  # 0. index contains successfully parsed args
    for path in opt_args.pop('handlers_path'):
        discovery.storage_handlers.add_discover_path(path)

    parser = argparse.ArgumentParser(
        description=('Entry point of automated building changed schedules. '
                     'Input provides up-to-date source (directory) and list of '
                     'changed files for further processing.'))

    parser.add_argument(*handlers_args_def, **handlers_kwargs_def)

    # TODO: remove
    parser.add_argument('--clean-checkout', action='store_true', default=False,
                        help='Remove previously fetched working copy (if '
                             'exists) of repository before doing updates.')

    parser.add_argument('--source-storage-format',
                        choices=discovery.storage_handlers.keys(),
                        metavar='SRC_STORAGE_FORMAT',
                        help='Source storage format to use')
    parser.add_argument('--cvs-checkout-path',
                        help='Path to shared working copy of CVS repository')
    parser.add_argument('--cvs-repo-name',
                        help='Name of CVS repository to checkout')
    parser.add_argument('--cvs-root',
                        help='Root of CVS repository')
    parser.add_argument('source',
                        help='Source schedule handle (file/URL/...)',
                        type=str,
                        metavar='SRC')

    arguments = parser.parse_args(args)
    opt_args = vars(arguments)

    # --handlers-path argument is already procesed, it shouldn't be passed
    # as opt_args into handlers
    opt_args.pop('handlers_path')

    updater = StorageUpdate(arguments.source,
                            arguments.source_storage_format,
                            opt_args)

if __name__ == '__main__':
    main(sys.argv[1:])
