#!/usr/bin/env python
import argparse
import os
import sys
import re
import logging
from schedules_tools import discovery
from schedules_tools import testrunner


logger = logging.getLogger(__name__)
handler_class_template = re.compile('^ScheduleHandler_(\S+)$')
BASE_DIR = os.path.dirname(os.path.realpath(
    os.path.join(__file__, os.pardir)))

# FIXME(mpavlase): Figure out nicer way to deal with paths
sys.path.append(BASE_DIR)


def setup_logging(level):
    log_format = '%(name)-10s %(levelname)7s: %(message)s'
    sh = logging.StreamHandler(sys.stdout)
    sh.setLevel(level)

    formatter = logging.Formatter(log_format)
    sh.setFormatter(formatter)

    # setup root logger
    inst = logging.getLogger('')
    inst.setLevel(level)
    inst.addHandler(sh)




def main(args):
    handlers_args_def = '--handlers-path',
    handlers_kwargs_def = {
        'help': 'Add python-dot-notation path to discover handlers (needs to '
                'be python module), can be called several times '
                '(conflicting names will be overriden - the last '
                'implementation will be used)',
        'action': 'append',
        'default': []
    }
    setup_logging(logging.DEBUG)

    # Separate parser to handle '--handlers-path' argument and prepare
    # converter.provided_exports to be used in main parser
    add_handler_parser = argparse.ArgumentParser(add_help=False)
    add_handler_parser.add_argument(*handlers_args_def, **handlers_kwargs_def)
    known_args = add_handler_parser.parse_known_args(args)

    opt_args = vars(known_args[0])  # 0. index contains successfully parsed args
    for path in opt_args.pop('handlers_path'):
        discovery.schedule_handlers.add_discover_path(path)
        discovery.storage_handlers.add_discover_path(path)

    parser = argparse.ArgumentParser(description='Perform schedule conversions.')

    parser.add_argument(*handlers_args_def, **handlers_kwargs_def)
    subparser = parser.add_mutually_exclusive_group()

    subparser.add_argument('--test-input',
                           help='Test input file',
                           type=str,
                           metavar='TEST_INPUT')
    subparser.add_argument('--test-output',
                           help='Test output file',
                           type=str,
                           metavar='TEST_OUTPUT')
    parser.add_argument('--json-reference',
                        help='JSON reference dump of intermediary Schedule '
                             'model',
                        type=str,
                        metavar='JSON_FILE')
    parser.add_argument('--dump-as-reference',
                        action='store_true')
    parser.add_argument('handler',
                        choices=discovery.schedule_handlers.keys(),
                        metavar='HANDLER',
                        help='Name of handler to test with given test files')

    arguments = parser.parse_args(args)
    opt_args = vars(arguments)

    # --handlers-path argument is already procesed, it shouldn't be passed
    # as opt_args into handlers
    opt_args.pop('handlers_path')

    runner = testrunner.TestRunner(arguments.handler,
                                   arguments.json_reference)
    if arguments.test_input:
        if arguments.dump_as_reference:
            runner.make_json_reference(arguments.test_input)
        else:
            runner.test_input(arguments.test_input)
    elif arguments.test_output:
        runner.test_output(arguments.test_output)


if __name__ == '__main__':
    main(sys.argv[1:])
