name: Pypi Upload

on:
  workflow_run:
    workflows: [Test]
    branches: [master]
    types: [completed]

  push:
    tags: '*'

  workflow_dispatch:


jobs:
  upload:

    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch also tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*
